version: '2'
services:
    fazanicrm-app:
        image: fazanicrm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://fazanicrm-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=FazaniCRM
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=fazanicrm-elasticsearch:9300
        ports:
            - 8080:8080
    fazanicrm-mongodb:
        extends:
            file: mongodb.yml
            service: fazanicrm-mongodb
    fazanicrm-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: fazanicrm-elasticsearch
